#!/usr/bin/env python3
"""Entry point for the carbon code optimizer."""

import argparse
import os
import sys

from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel

load_dotenv()

from optimizer import build_graph
from optimizer.state import PYTHON, TEST_FILE, UNOPTIMIZED_FILE, OptimizationState

console = Console()


def main():
    parser = argparse.ArgumentParser(
        description="Carbon code optimizer — optimize Python functions to reduce CO2 emissions."
    )
    parser.add_argument(
        "--input",
        metavar="FILE",
        help="Path to the Python file to optimize (default: input_data/unoptimized_code.py)",
    )
    parser.add_argument(
        "--venv",
        metavar="PYTHON",
        help="Path to the target venv Python interpreter (default: local venv)",
    )
    parser.add_argument(
        "--tests",
        metavar="FILE",
        help="Path to existing test file (optional — Claude generates tests if omitted)",
    )
    parser.add_argument(
        "--max-attempts",
        type=int,
        default=5,
        metavar="N",
        help="Max optimization attempts per function (default: 5)",
    )
    args = parser.parse_args()

    if not os.environ.get("ANTHROPIC_API_KEY"):
        console.print("[red]Error: ANTHROPIC_API_KEY not set. Create a .env file.[/red]")
        sys.exit(1)

    # Resolve input file
    if args.input:
        input_file = os.path.abspath(args.input)
    else:
        input_file = UNOPTIMIZED_FILE

    if not os.path.isfile(input_file):
        console.print(f"[red]Error: input file not found: {input_file}[/red]")
        sys.exit(1)

    # Resolve Python interpreter
    target_python = args.venv if args.venv else PYTHON

    # Read source file
    with open(input_file) as f:
        full_source = f.read()

    # Resolve test file
    raw_test_file = ""
    if args.tests:
        with open(args.tests) as f:
            raw_test_file = f.read()
    elif args.input is None:
        # Default mode: use the bundled TEST_FILE if present
        try:
            with open(TEST_FILE) as f:
                raw_test_file = f.read()
        except FileNotFoundError:
            raw_test_file = ""

    console.print(
        Panel(
            f"Input:        {input_file}\n"
            f"Interpreter:  {target_python}\n"
            f"Tests:        {'provided' if raw_test_file else 'will be generated by Claude'}\n"
            f"Max attempts: {args.max_attempts} per function",
            title="Carbon Code Optimizer",
            border_style="blue",
        )
    )

    initial_state: OptimizationState = {
        # File-level context
        "input_file": input_file,
        "target_python": target_python,
        "all_functions": [],
        "file_preamble": "",
        "full_source": full_source,
        "raw_test_file": raw_test_file,
        "current_func_idx": 0,
        "function_results": {},
        # Per-function fields (populated by find_or_create_spec)
        "unoptimized_code": "",
        "test_code": "",
        "current_code": "",
        "baseline_emissions": 0.0,
        "current_emissions": 0.0,
        "attempt": 0,
        "max_attempts": args.max_attempts,
        "feedback": [],
        "best_code": "",
        "best_emissions": float("inf"),
        "done": False,
        "test_passed": False,
        "carbon_improved": False,
    }

    graph = build_graph()
    graph.invoke(initial_state)


if __name__ == "__main__":
    main()
